### ISSUE TITLE
Update docs with thoughts on reponsibility and data ownership (case 14678)

### ISSUE THREAD

**Issue by buep** [Praqma/automated-branch-pipelines#10]
I would like to revisit the design, explaining views on which components own and have access to data, where it would be natural to have the data available etc.

Timeboxed 1-2 hours.

**Comment by buep** [comment]
Changed on my branch, I have asked Martin to do sanity check.

Then I will notify Josra slack channel to get help on decision and inputs... including Lars.

**Comment by martinmosegaard** [comment]
Added review comments, just minor typos.
