### ISSUE TITLE
Update project config document with new suggestions

### ISSUE THREAD

**Issue by martinmosegaard** [Praqma/automated-branch-pipelines#9]

**Comment by buep** [comment]
What is this about?

**Comment by buep** [comment]
Tjek #10 - I'm doing a little write-up to help us decide on the design change or implementation suggested related to #8.

**Comment by martinmosegaard** [comment]
I added a bit on what we talked about yesterday. Please elaborate with your thoughts, for example on the stateful service.

**Comment by lakruzz** [comment]
@martinmosegaard your commit 	3012666 never made it to master - is the pipeline not running?

**Comment by martinmosegaard** [comment]
@lakruzz This project does not have a pipeline yet itself ... I will manually merge it to master.
